# Generated by Django 5.2.11 on 2026-02-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appvariety',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='appvariety',
            name='image',
            field=models.ImageField(upload_to='apps/'),
        ),
    ]
